pipelines:
  branches:
    master:
      - step:
         name: Deploying on 134.209.183.27 nginx
         script:
           - pipe: atlassian/ssh-run:0.2.6
             variables:
               SSH_USER: "root"
               SERVER: "134.209.183.27"
               COMMAND: "/root/clone.sh"
               MODE: "command"