pipelines:
  branches:
    master:
      - parallel:
         - step:
            name: Deploying on 178.128.43.46 nginx
            script:
              - pipe: atlassian/ssh-run:0.2.6
                variables:
                  SSH_USER: "root"
                  SERVER: "178.128.43.46"
                  COMMAND: "/root/clone.sh"
                  MODE: "command"
         - step:
            name: Deploying on 178.128.43.46 litespeed
            script:
              - pipe: atlassian/ssh-run:0.2.6
                variables:
                  SSH_USER: "root"
                  SERVER: "178.128.43.46"
                  COMMAND: "/root/clone.litespeed.sh"
                  MODE: "command"
