pipelines:
  branches:
    main:
      - parallel:
         - step:
            name: Deploying on  134.209.183.27 nginx
            script:
              - pipe: atlassian/ssh-run:0.2.6
                variables:
                  SSH_USER: "root"
                  SERVER: "134.209.183.27"
                  COMMAND: "/root/clone.sh"
                  MODE: "command"
         - step:
            name: Deploying on 178.128.43.46 litespeed
            script:
              - pipe: atlassian/ssh-run:0.2.6
                variables:
                  SSH_USER: "root"
                  SERVER: "134.209.183.27"
                  COMMAND: "/root/clone.lightspeed.sh"
                  MODE: "command"
         - step:
            name: Deploying on 138.68.141.175 litespeed
            script:
              - pipe: atlassian/ssh-run:0.2.6
                variables:
                  SSH_USER: "root"
                  SERVER: "138.68.141.175"
                  COMMAND: "/root/clone.litespeed.sh"
                  MODE: "command"
