name: Deployment

on:
  push:
    branches: 
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH Execute Commands
        uses: appleboy/ssh-action@master
        with:
          host: 143.110.190.203
          username: root
          script: /root/clone.sh
          key: ${{ secrets.KEY }}
